# Site settings
title: PegelAlarm
email: info@pegelalarm.org
url: https://pegelalarm.org
description: "Pegel Alarm ist eine kostenlose Android App die einem dabei hilft Wasserstände von Flüssen und Seen im Auge zu behalten."

# Color settings
color:
  primary-light: '#FFFFFF'
  primary-medium: '#333333'
  blue: '#6699FF'
  links: '#219ab3'

# Footer settings
footer: PegelAlarm

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jvalue/hochwasser-app

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html


paginate: 5
paginate_path: "/blog/page:num/"
